### ISSUE TITLE
V1.0 TODO list

### ISSUE THREAD

**Issue by amanusk** [amanusk/s-tui#110]
- [x] Better naming for sensors

- [x] Save settings for sensors

- [x] Do not display empty sensors

- [x] Fix json print

- [x] Fix tests

- [ ] Gil's necromancer improvements
